FROM alpine:latest
MAINTAINER Simone Basso (bassosimone@gmail.com)
RUN apk add cmake g++ curl-dev make               \
    curl autoconf automake libtool file           \
    libevent-dev libmaxminddb-dev linux-headers
