#!/usr/bin/env python

#
# Copyright (c) 2013
#     Nexa Center for Internet & Society, Politecnico di Torino (DAUIN)
#     and Simone Basso <bassosimone@gmail.com>.
#
# This file is part of Neubot <http://www.neubot.org/>.
#
# Neubot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Neubot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
#

import json
import sys

CLANG_TYPE = {
    "Object": "void *",
    "cstring": "const char *",
    "void_p": "void *",
}

def clang_comment(string):
    sys.stdout.write("/* %s */\n" % string)

def clang_empty_line():
    sys.stdout.write("\n")

def clang_write_copyright():
    sys.stdout.write("/*\n")
    sys.stdout.write(" * LibNeubot interface - Public domain.\n")
    sys.stdout.write(" */\n")

def clang_type(name):
    return CLANG_TYPE.get(name, name)

def clang_declare_callback(retval, cbname, params):
    sys.stdout.write("typedef %s (*%s)(" % (retval, cbname))
    for index, elem in enumerate(params):
        name, value = elem
        name = clang_type(name)
        sys.stdout.write("%s" % name)
        if index < len(params) - 1:
            sys.stdout.write(", ")
    sys.stdout.write(");\n")

def clang_declare_class(name):
    sys.stdout.write("struct %s;\n" % name)
    CLANG_TYPE[name] = "struct " + name
    CLANG_TYPE[name + "_p"] = "struct " + name + " *"

def clang_declare_method(name, method):

    if method[0] == "__construct__":
        retval = name + "_p"
        funcname = name + "_construct"
        args = method[1:]
    else:
        retval = method[0]
        funcname = name + "_" + method[1]
        args = method[2:]
        args.insert(0, (name + "_p", "self"))

    retval = clang_type(retval)
    sys.stdout.write("%s %s(" % (retval, funcname))
    if args:
        for index, elem in enumerate(args):
            name, value = elem
            name = clang_type(name)
            sys.stdout.write("%s" % name)
            if index < len(args) - 1:
                sys.stdout.write(", ")
    else:
        sys.stdout.write("void")
    sys.stdout.write(");\n")

def main():
    path = sys.argv[1]
    filep = open(path, "r")
    interface = json.load(filep)

    clang_write_copyright()

    clang_empty_line()
    clang_comment("Classes:")
    clang_empty_line()

    for name in sorted(interface["classes"]):
        clang_declare_class(name)

    clang_empty_line()
    clang_comment("Callbacks:")
    clang_empty_line()

    for callback in interface["callbacks"]:
        retval = callback[0]
        name = callback[1]
        params = callback[2:]
        clang_declare_callback(retval, name, params)

    clang_empty_line()

    for name in sorted(interface["classes"]):
        clang_comment("%s API:" % name)
        clang_empty_line()
        for method in interface["classes"][name]:
            clang_declare_method(name, method)
            clang_empty_line()

if __name__ == "__main__":
    main()
