/*
 * LibNeubot interface - Public domain.
 * WARNING: Autogenerated file - do not edit!
 */

/* Classes: */

struct NeubotEchoServer;
struct NeubotPollable;
struct NeubotPoller;

/* Callbacks: */

typedef void (*NeubotPoller_resolve_callback)(void *, const char *);
typedef void (*NeubotPoller_callback)(void *);
typedef void (*NeubotPollable_callback)(void *);

/* NeubotEchoServer API: */

struct NeubotEchoServer *NeubotEchoServer_construct(struct NeubotPoller *, 
    int, const char *, const char *);

/* NeubotPollable API: */

struct NeubotPollable *NeubotPollable_construct(struct NeubotPoller *, 
    NeubotPollable_callback, NeubotPollable_callback, NeubotPollable_callback, 
    void *);

int NeubotPollable_attach(struct NeubotPollable *, long long);

void NeubotPollable_detach(struct NeubotPollable *);

long long NeubotPollable_fileno(struct NeubotPollable *);

int NeubotPollable_set_readable(struct NeubotPollable *);

int NeubotPollable_unset_readable(struct NeubotPollable *);

int NeubotPollable_set_writable(struct NeubotPollable *);

int NeubotPollable_unset_writable(struct NeubotPollable *);

void NeubotPollable_set_timeout(struct NeubotPollable *, double);

void NeubotPollable_clear_timeout(struct NeubotPollable *);

void NeubotPollable_close(struct NeubotPollable *);

/* NeubotPoller API: */

struct NeubotPoller *NeubotPoller_construct(void);

int NeubotPoller_sched(struct NeubotPoller *, double, NeubotPoller_callback, 
    void *);

int NeubotPoller_defer_read(struct NeubotPoller *, long long, 
    NeubotPoller_callback, NeubotPoller_callback, void *, double);

int NeubotPoller_defer_write(struct NeubotPoller *, long long, 
    NeubotPoller_callback, NeubotPoller_callback, void *, double);

int NeubotPoller_resolve(struct NeubotPoller *, int, const char *, 
    NeubotPoller_resolve_callback, void *);

void NeubotPoller_loop(struct NeubotPoller *);

void NeubotPoller_break_loop(struct NeubotPoller *);

