// Part of measurement-kit <https://measurement-kit.github.io/>.
// Measurement-kit is free software under the BSD license. See AUTHORS
// and LICENSE for more information on the copying conditions.
#ifndef MEASUREMENT_KIT_COMMON_VERSION_HPP
#define MEASUREMENT_KIT_COMMON_VERSION_HPP

// File generated by `./autogen.sh` containing the exact version
#include <measurement_kit/common/git_version.hpp>

/// `MK_VERSION` is MK version expressed using semantic versioning.
#define MK_VERSION "0.8.0-alpha"

#define MEASUREMENT_KIT_VERSION MK_VERSION /* Backward compatibility */

#ifdef __cplusplus
extern "C" {
#endif

/// `mk_version` returns MK version.
const char *mk_version(void);

/// \brief `mk_version_full` returns the result of `git describe --tags`
/// as run when generating a release tarball or a development build.
/// This is a more comprehensive (hence "full") description of the current
/// version. At a release point, it must be equal to mk_version(). For
/// development builds it may differ. It will indicate the closest in
/// history tag, the number of commits since that tag, and the initial
/// part of the SHA1 of the tip of the current branch.
const char *mk_version_full(void);

/// `mk_openssl_version()` returns the OpenSSL version that we link with.
const char *mk_openssl_version(void);

/// `mk_libevent_version()` returns the libevent version that we link with.
const char *mk_libevent_version(void);

#ifdef __cplusplus
} // namespace mk
#endif
#endif
