#!/bin/sh
set -e

usage="Usage: $0 [--disable-binaries] [--disable-examples] [--disable-tests] msvc|gcc"

enable_examples=1
enable_binaries=1
enable_tests=1
while [ $# -gt 0 ]; do
  case "$1" in
    --disable-examples)
      enable_examples=0
      shift;;
    --disable-binaries)
      enable_binaries=0
      shift;;
    --disable-tests)
      enable_tests=0
      shift;;
    -*)
      echo "$usage" 1>&2
      exit 1;;
    --)
      shift; break;;
    *)
      break;;
  esac
done
if [ $# -ne 1 -a "$1" != "mscv" -a "$1" != "gcc" ]; then
  echo "$usage" 1>&2
  exit 1
fi

if [ "$1" = "msvc" ]; then
  cp script/ninja/rules.mscv.ninja rules.ninja
  libprefix=
  exeext=.exe
  objext=.obj
  libext=.lib
elif [ "$1" = "gcc" ]; then
  libprefix=lib
  exeext=
  objext=.o
  libext=.a
else
  echo "FATAL: unexpected target: $1" 1>&2
  exit 1
fi

export libprefix exeext objext libext

./script/ninja/gen-rules-$1 > build.ninja
./script/ninja/gen-build-libmk >> build.ninja
if [ $enable_binaries -ne 0 ]; then
  ./script/ninja/gen-build-mk >> build.ninja
fi
if [ $enable_examples -ne 0 ]; then
  ./script/ninja/gen-build-examples >> build.ninja
fi
if [ $enable_tests -ne 0 ]; then
  ./script/ninja/gen-build-tests >> build.ninja
fi
