#!/bin/sh
set -e

echo ""
lib_objects=""
for src in `find src/libmeasurement_kit -type f -name \*.c -o -name \*.cpp`; do
  if echo $src | grep -q '.c$'; then
    obj=`echo $src|sed -e "s/.c$/$objext/g"`
    echo "build $obj: cc $src"
    lib_objects="$lib_objects $obj"
  elif echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e "s/.cpp$/$objext/g"`
    echo "build $obj: cxx $src"
    lib_objects="$lib_objects $obj"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
echo ""
echo "build ${libprefix}measurement_kit$libext: ar $lib_objects"
