#!/bin/sh
set -e

if [ $# -eq 0 ]; then
  $0 --gen > build.ninja
  exit 1
fi

echo "include rules.ninja"
echo ""

echo ""
lib_objects=""
for src in `find src/libmeasurement_kit -type f -name \*.c -o -name \*.cpp`; do
  if echo $src | grep -q '.c$'; then
    obj=`echo $src|sed -e 's/.c$/.o/g'`
    echo "build $obj: cc $src"
    lib_objects="$lib_objects $obj"
  elif echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e 's/.cpp$/.o/g'`
    echo "build $obj: cxx $src"
    lib_objects="$lib_objects $obj"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
echo ""
echo "build libmeasurement_kit.a: ar $lib_objects"
echo ""

echo ""
bin_objects=""
for src in `find src/measurement_kit -type f -name \*c -o -name \*.cpp`; do
  if echo $src | grep -q '.c$'; then
    obj=`echo $src|sed -e 's/.c$/.o/g'`
    echo "build $obj: cc $src"
    bin_objects="$bin_objects $obj"
  elif echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e 's/.cpp$/.o/g'`
    echo "build $obj: cxx $src"
    bin_objects="$bin_objects $obj"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
echo ""
echo "build measurement_kit$ext: link $bin_objects libmeasurement_kit.a"

echo ""
for src in `find example -type f -name \*.cpp`; do
  if echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e 's/.cpp$/.o/g'`
    bin=`echo $src|sed -e 's/.cpp$//g'`
    echo "build $obj: cxx $src"
    echo "build $bin$ext: link $obj libmeasurement_kit.a"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done

echo ""
for src in `find test -type f -name \*.cpp`; do
  if echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e 's/.cpp$/.o/g'`
    bin=`echo $src|sed -e 's/.cpp$//g'`
    echo "build $obj: cxx $src"
    echo "build $bin$ext: link $obj libmeasurement_kit.a"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
