#!/bin/sh
set -e

if [ $# -eq 0 ]; then
  cp script/ninja/rules.mscv.ninja rules.ninja
  $0 --gen > build.ninja
  exit 0
fi

libprefix=
exeext=.exe
objext=.obj
libext=.lib

echo "ninja_required_version = 1.1"
echo "include rules.ninja"
echo ""

echo ""
lib_objects=""
for src in `find src/libmeasurement_kit -type f -name \*.c -o -name \*.cpp`; do
  if echo $src | grep -q '.c$'; then
    obj=`echo $src|sed -e "s/.c$/$objext/g"`
    echo "build $obj: cc $src"
    lib_objects="$lib_objects $obj"
  elif echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e "s/.cpp$/$objext/g"`
    echo "build $obj: cxx $src"
    lib_objects="$lib_objects $obj"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
echo ""
echo "build ${libprefix}measurement_kit$libext: ar $lib_objects"
echo ""

echo ""
bin_objects=""
for src in `find src/measurement_kit -type f -name \*c -o -name \*.cpp`; do
  if echo $src | grep -q '.c$'; then
    obj=`echo $src|sed -e "s/.c$/$objext/g"`
    echo "build $obj: cc $src"
    bin_objects="$bin_objects $obj"
  elif echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e "s/.cpp$/$objext/g"`
    echo "build $obj: cxx $src"
    bin_objects="$bin_objects $obj"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
echo ""
echo "build measurement_kit$exeext: link $bin_objects ${libprefix}measurement_kit$libext"

echo ""
for src in `find example -type f -name \*.cpp`; do
  if echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e "s/.cpp$/$objext/g"`
    bin=`echo $src|sed -e 's/.cpp$//g'`
    echo "build $obj: cxx $src"
    echo "build $bin$exeext: link $obj ${libprefix}measurement_kit$libext"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done

echo ""
for src in `find test -type f -name \*.cpp`; do
  if echo $src | grep -q '.cpp$'; then
    bin=`echo $src|sed -e 's/.cpp$//g'`
    obj=`echo $src|sed -e "s/.cpp$/$objext/g"`
    echo "build $obj: cxx $src"
    echo "build $bin$exeext: link $obj ${libprefix}measurement_kit$libext"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
