#!/bin/sh
set -e

echo ""
bin_objects=""
for src in `find src/measurement_kit -type f -name \*c -o -name \*.cpp`; do
  if echo $src | grep -q '.c$'; then
    obj=`echo $src|sed -e "s/.c$/$objext/g"`
    echo "build $obj: cc $src"
    bin_objects="$bin_objects $obj"
  elif echo $src | grep -q '.cpp$'; then
    obj=`echo $src|sed -e "s/.cpp$/$objext/g"`
    echo "build $obj: cxx $src"
    bin_objects="$bin_objects $obj"
  else
    echo "FATAL: unexpected file extension: $src" 1>&2
    exit 1
  fi
done
echo ""
echo "build measurement_kit$exeext: link $bin_objects ${libprefix}measurement_kit$libext"
