#!/bin/sh
set -e
if [ "$CC" = "" ]; then
  CC=cc
fi
if [ "$CXX" = "" ]; then
  CXX=c++
fi
if [ "$AR" = "" ]; then
  AR=ar
fi
if [ "$CPPFLAGS" = "" ]; then
  CPPFLAGS="-pthread -DHTTP_PARSER_STRICT=0 -DENABLE_INTEGRATION_TESTS -DENABLE_TRACEROUTE"
fi
if [ "$CFLAGS" = "" ]; then
  CFLAGS="-pedantic -O2"
fi
if [ "$CXXFLAGS" = "" ]; then
  CXXFLAGS="-pedantic -O2"
fi
if [ "$LDFLAGS" = "" ]; then
  LDFLAGS="-pthread"
fi
if [ "$LIBS" = "" ]; then
  LIBS="-lcrypto -lssl -levent -levent_pthreads -levent_openssl -lGeoIP -lresolv"
fi
sed -e "s|@CPPFLAGS@|$CPPFLAGS|g"                                              \
    -e "s|@CFLAGS@|$CFLAGS|g"                                                  \
    -e "s|@CXXFLAGS@|$CXXFLAGS|g"                                              \
    -e "s|@CC@|$CC|g"                                                          \
    -e "s|@CXX@|$CXX|g"                                                        \
    -e "s|@AR@|$AR|g"                                                          \
    -e "s|@LDFLAGS@|$LDFLAGS|g"                                                \
    -e "s|@LIBS@|$LIBS|g"                                                      \
    script/ninja/rules.gcc.ninja.in
