// Part of Measurement Kit <https://measurement-kit.github.io/>.
// Measurement Kit is free software under the BSD license. See AUTHORS
// and LICENSE for more information on the copying conditions.
#ifndef MEASUREMENT_KIT_FFI_MACROS_H
#define MEASUREMENT_KIT_FFI_MACROS_H

/*-
 *  __      __  _____ __________  _______  .___ _______    ________
 * /  \    /  \/  _  \\______   \ \      \ |   |\      \  /  _____/
 * \   \/\/   /  /_\  \|       _/ /   |   \|   |/   |   \/   \  ___
 *  \        /    |    \    |   \/    |    \   /    |    \    \_\  \
 *   \__/\  /\____|__  /____|_  /\____|__  /___\____|__  /\______  /
 *        \/         \/       \/         \/            \/        \/
 *
 * Autogenerated by `./script/autoapi/autoapi`. DO NOT EDIT!!!
 */

/* MK_ENUM_EVENTS(name, type, mandatory) */
#define MK_ENUM_EVENTS(XX) \
  XX(failure.asn_lookup, object, false) \
  XX(failure.cc_lookup, object, false) \
  XX(failure.ip_lookup, object, false) \
  XX(failure.measurement, object, false) \
  XX(failure.measurement_submission, object, false) \
  XX(failure.report_create, object, false) \
  XX(failure.report_close, object, false) \
  XX(failure.resolver_lookup, object, false) \
  XX(failure.startup, object, false) \
  XX(log, object, false) \
  XX(measurement, object, false) \
  XX(status.end, object, false) \
  XX(status.geoip_lookup, object, false) \
  XX(status.progress, object, false) \
  XX(status.queued, object, false) \
  XX(status.measurement_start, object, false) \
  XX(status.measurement_submission, object, false) \
  XX(status.measurement_done, object, false) \
  XX(status.report_close, object, false) \
  XX(status.report_create, object, false) \
  XX(status.resolver_lookup, object, false) \
  XX(status.started, object, false) \
  XX(status.update.performance, object, false) \
  XX(status.update.websites, object, false) \
  XX(task_terminated, object, false)

/* MK_ENUM_LOG_LEVELS(name, type, mandatory) */
#define MK_ENUM_LOG_LEVELS(XX) \
  XX(ERR, string, false) \
  XX(WARNING, string, false) \
  XX(INFO, string, false) \
  XX(DEBUG, string, false) \
  XX(DEBUG2, string, false)

/* MK_ENUM_OPTIONS(name, type, mandatory) */
#define MK_ENUM_OPTIONS(XX) \
  XX(bouncer_base_url, string, false) \
  XX(collector_base_url, string, false) \
  XX(dns/nameserver, string, false) \
  XX(dns/engine, string, false) \
  XX(geoip_asn_path, string, false) \
  XX(geoip_country_path, string, false) \
  XX(ignore_bouncer_error, number_integer, false) \
  XX(ignore_open_report_error, number_integer, false) \
  XX(max_runtime, number_float, false) \
  XX(net/ca_bundle_path, string, false) \
  XX(net/timeout, number_float, false) \
  XX(no_bouncer, number_integer, false) \
  XX(no_collector, number_integer, false) \
  XX(no_asn_lookup, number_integer, false) \
  XX(no_cc_lookup, number_integer, false) \
  XX(no_ip_lookup, number_integer, false) \
  XX(no_file_report, number_integer, false) \
  XX(no_resolver_lookup, number_integer, false) \
  XX(probe_asn, string, false) \
  XX(probe_cc, string, false) \
  XX(probe_ip, string, false) \
  XX(randomize_input, number_integer, false) \
  XX(save_real_probe_asn, number_integer, false) \
  XX(save_real_probe_cc, number_integer, false) \
  XX(save_real_probe_ip, number_integer, false) \
  XX(save_real_resolver_ip, number_integer, false) \
  XX(software_name, string, false) \
  XX(software_version, string, false)

/* MK_ENUM_SETTINGS(name, type, mandatory) */
#define MK_ENUM_SETTINGS(XX) \
  XX(annotations, object, false) \
  XX(disabled_events, array, false) \
  XX(inputs, array, false) \
  XX(input_filepaths, array, false) \
  XX(log_filepath, string, false) \
  XX(log_level, string, false) \
  XX(name, string, true) \
  XX(options, object, false) \
  XX(output_filepath, string, false)

/* MK_ENUM_TASKS(name, type, mandatory) */
#define MK_ENUM_TASKS(XX) \
  XX(CaptivePortal, string, false) \
  XX(Dash, string, false) \
  XX(DnsInjection, string, false) \
  XX(FacebookMessenger, string, false) \
  XX(HttpHeaderFieldManipulation, string, false) \
  XX(HttpInvalidRequestLine, string, false) \
  XX(MeekFrontedRequests, string, false) \
  XX(MultiNdt, string, false) \
  XX(Ndt, string, false) \
  XX(TcpConnect, string, false) \
  XX(Telegram, string, false) \
  XX(WebConnectivity, string, false) \
  XX(Whatsapp, string, false)

#endif /* MEASUREMENT_KIT_FFI_MACROS_H */
