// File autogenerated by `./autogen.sh`, do not edit
#ifndef MEASUREMENT_KIT_NETTESTS_HPP
#define MEASUREMENT_KIT_NETTESTS_HPP
#include <measurement_kit/nettests/base_test.hpp>
#include <measurement_kit/nettests/dns_injection.hpp>
#include <measurement_kit/nettests/http_invalid_request_line.hpp>
#include <measurement_kit/nettests/meek_fronting.hpp>
#include <measurement_kit/nettests/multi_ndt.hpp>
#include <measurement_kit/nettests/ndt.hpp>
#include <measurement_kit/nettests/runnable.hpp>
#include <measurement_kit/nettests/runner.hpp>
#include <measurement_kit/nettests/tcp_connect.hpp>
#include <measurement_kit/nettests/web_connectivity.hpp>
#endif
