// File autogenerated by `./autogen.sh`, do not edit
#ifndef MEASUREMENT_KIT_REPORT_HPP
#define MEASUREMENT_KIT_REPORT_HPP
#include <measurement_kit/report/base_reporter.hpp>
#include <measurement_kit/report/entry.hpp>
#include <measurement_kit/report/error.hpp>
#include <measurement_kit/report/file_reporter.hpp>
#endif
