/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_measurement_kit_common_Async */

#ifndef _Included_io_github_measurement_kit_common_Async
#define _Included_io_github_measurement_kit_common_Async
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_measurement_kit_common_Async
 * Method:    runTest
 * Signature: (Lio/github/measurement_kit/common/NetTest;Lio/github/measurement_kit/common/TestComplete;)V
 */
JNIEXPORT void JNICALL Java_io_github_measurement_1kit_common_Async_runTest
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     io_github_measurement_kit_common_Async
 * Method:    loopOnce
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_measurement_1kit_common_Async_loopOnce
  (JNIEnv *, jobject);

/*
 * Class:     io_github_measurement_kit_common_Async
 * Method:    alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_measurement_1kit_common_Async_alloc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class io_github_measurement_kit_common_NetTest */

#ifndef _Included_io_github_measurement_kit_common_NetTest
#define _Included_io_github_measurement_kit_common_NetTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_measurement_kit_common_NetTest
 * Method:    allocTest
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_measurement_1kit_common_NetTest_allocTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class io_github_measurement_kit_common_TestComplete */

#ifndef _Included_io_github_measurement_kit_common_TestComplete
#define _Included_io_github_measurement_kit_common_TestComplete
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_measurement_kit_common_Logger */

#ifndef _Included_io_github_measurement_kit_common_Logger
#define _Included_io_github_measurement_kit_common_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_measurement_kit_common_Logger
 * Method:    setVerbose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_measurement_1kit_common_Logger_setVerbose
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_measurement_kit_common_Logger
 * Method:    useAndroidLogger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_measurement_1kit_common_Logger_useAndroidLogger
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
