/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_measurement_kit_ooni_TCPConnect */

#ifndef _Included_io_github_measurement_kit_ooni_TCPConnect
#define _Included_io_github_measurement_kit_ooni_TCPConnect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_measurement_kit_ooni_TCPConnect
 * Method:    allocTest
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_measurement_1kit_ooni_TCPConnect_allocTest
  (JNIEnv *, jobject);

/*
 * Class:     io_github_measurement_kit_ooni_DNSInjection
 * Method:    allocTest
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_measurement_1kit_ooni_DNSInjection_allocTest
  (JNIEnv *, jobject);

/*
 * Class:     io_github_measurement_kit_ooni_HTTPInvalidRequestLine
 * Method:    allocTest
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_measurement_1kit_ooni_HTTPInvalidRequestLine_allocTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
