#!/bin/sh
# This is the script run for CMake builds. At least mkcurl uses it.
set -ex
REPOROOT=$(cd $(dirname $0)/../../../ && pwd -P)
cd $REPOROOT
env|grep -v TOKEN|sort
tc qdisc add dev eth0 root netem delay 200ms 10ms # Reduce speed
cmake $CMAKE_OPTIONS .
cmake --build . -- $CMAKE_BUILD_OPTIONS
ctest $CTEST_OPTIONS
if [ "$BUILD_TYPE" = "coverage" ]; then
  lcov --directory . --capture -o lcov.info
  curl -fsSL -o codecov.sh https://codecov.io/bash
  bash codecov.sh -X gcov -f lcov.info
fi
