/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA
#define SWIG_DIRECTORS


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else

/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes that proxy
 * method calls from C++ to Java extensions.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus

#if defined(DEBUG_DIRECTOR_OWNED)
#include <iostream>
#endif

namespace Swig {
  /* Java object wrapper */
  class JObjectWrapper {
  public:
    JObjectWrapper() : jthis_(NULL), weak_global_(true) {
    }

    ~JObjectWrapper() {
      jthis_ = NULL;
      weak_global_ = true;
    }

    bool set(JNIEnv *jenv, jobject jobj, bool mem_own, bool weak_global) {
      if (!jthis_) {
        weak_global_ = weak_global || !mem_own; // hold as weak global if explicitly requested or not owned
        if (jobj)
          jthis_ = weak_global_ ? jenv->NewWeakGlobalRef(jobj) : jenv->NewGlobalRef(jobj);
#if defined(DEBUG_DIRECTOR_OWNED)
        std::cout << "JObjectWrapper::set(" << jobj << ", " << (weak_global ? "weak_global" : "global_ref") << ") -> " << jthis_ << std::endl;
#endif
        return true;
      } else {
#if defined(DEBUG_DIRECTOR_OWNED)
        std::cout << "JObjectWrapper::set(" << jobj << ", " << (weak_global ? "weak_global" : "global_ref") << ") -> already set" << std::endl;
#endif
        return false;
      }
    }

    jobject get(JNIEnv *jenv) const {
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "JObjectWrapper::get(";
      if (jthis_)
        std::cout << jthis_;
      else
        std::cout << "null";
      std::cout << ") -> return new local ref" << std::endl;
#endif
      return (jthis_ ? jenv->NewLocalRef(jthis_) : jthis_);
    }

    void release(JNIEnv *jenv) {
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "JObjectWrapper::release(" << jthis_ << "): " << (weak_global_ ? "weak global ref" : "global ref") << std::endl;
#endif
      if (jthis_) {
        if (weak_global_) {
          if (jenv->IsSameObject(jthis_, NULL) == JNI_FALSE)
            jenv->DeleteWeakGlobalRef((jweak)jthis_);
        } else
          jenv->DeleteGlobalRef(jthis_);
      }

      jthis_ = NULL;
      weak_global_ = true;
    }

    /* Only call peek if you know what you are doing wrt to weak/global references */
    jobject peek() {
      return jthis_;
    }

    /* Java proxy releases ownership of C++ object, C++ object is now
       responsible for destruction (creates NewGlobalRef to pin Java
       proxy) */
    void java_change_ownership(JNIEnv *jenv, jobject jself, bool take_or_release) {
      if (take_or_release) {  /* Java takes ownership of C++ object's lifetime. */
        if (!weak_global_) {
          jenv->DeleteGlobalRef(jthis_);
          jthis_ = jenv->NewWeakGlobalRef(jself);
          weak_global_ = true;
        }
      } else { /* Java releases ownership of C++ object's lifetime */
        if (weak_global_) {
          jenv->DeleteWeakGlobalRef((jweak)jthis_);
          jthis_ = jenv->NewGlobalRef(jself);
          weak_global_ = false;
        }
      }
    }

  private:
    /* pointer to Java object */
    jobject jthis_;
    /* Local or global reference flag */
    bool weak_global_;
  };

  /* director base class */
  class Director {
    /* pointer to Java virtual machine */
    JavaVM *swig_jvm_;

  protected:
#if defined (_MSC_VER) && (_MSC_VER<1300)
    class JNIEnvWrapper;
    friend class JNIEnvWrapper;
#endif
    /* Utility class for managing the JNI environment */
    class JNIEnvWrapper {
      const Director *director_;
      JNIEnv *jenv_;
      int env_status;
    public:
      JNIEnvWrapper(const Director *director) : director_(director), jenv_(0), env_status(0) {
#if defined(__ANDROID__)
        JNIEnv **jenv = &jenv_;
#else
        void **jenv = (void **)&jenv_;
#endif
        env_status = director_->swig_jvm_->GetEnv((void **)&jenv_, JNI_VERSION_1_2);
#if defined(SWIG_JAVA_ATTACH_CURRENT_THREAD_AS_DAEMON)
        // Attach a daemon thread to the JVM. Useful when the JVM should not wait for 
        // the thread to exit upon shutdown. Only for jdk-1.4 and later.
        director_->swig_jvm_->AttachCurrentThreadAsDaemon(jenv, NULL);
#else
        director_->swig_jvm_->AttachCurrentThread(jenv, NULL);
#endif
      }
      ~JNIEnvWrapper() {
#if !defined(SWIG_JAVA_NO_DETACH_CURRENT_THREAD)
        // Some JVMs, eg jdk-1.4.2 and lower on Solaris have a bug and crash with the DetachCurrentThread call.
        // However, without this call, the JVM hangs on exit when the thread was not created by the JVM and creates a memory leak.
        if (env_status == JNI_EDETACHED)
          director_->swig_jvm_->DetachCurrentThread();
#endif
      }
      JNIEnv *getJNIEnv() const {
        return jenv_;
      }
    };

    /* Java object wrapper */
    JObjectWrapper swig_self_;

    /* Disconnect director from Java object */
    void swig_disconnect_director_self(const char *disconn_method) {
      JNIEnvWrapper jnienv(this) ;
      JNIEnv *jenv = jnienv.getJNIEnv() ;
      jobject jobj = swig_self_.get(jenv);
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "Swig::Director::disconnect_director_self(" << jobj << ")" << std::endl;
#endif
      if (jobj && jenv->IsSameObject(jobj, NULL) == JNI_FALSE) {
        jmethodID disconn_meth = jenv->GetMethodID(jenv->GetObjectClass(jobj), disconn_method, "()V");
        if (disconn_meth) {
#if defined(DEBUG_DIRECTOR_OWNED)
          std::cout << "Swig::Director::disconnect_director_self upcall to " << disconn_method << std::endl;
#endif
          jenv->CallVoidMethod(jobj, disconn_meth);
        }
      }
      jenv->DeleteLocalRef(jobj);
    }

  public:
    Director(JNIEnv *jenv) : swig_jvm_((JavaVM *) NULL), swig_self_() {
      /* Acquire the Java VM pointer */
      jenv->GetJavaVM(&swig_jvm_);
    }

    virtual ~Director() {
      JNIEnvWrapper jnienv(this) ;
      JNIEnv *jenv = jnienv.getJNIEnv() ;
      swig_self_.release(jenv);
    }

    bool swig_set_self(JNIEnv *jenv, jobject jself, bool mem_own, bool weak_global) {
      return swig_self_.set(jenv, jself, mem_own, weak_global);
    }

    jobject swig_get_self(JNIEnv *jenv) const {
      return swig_self_.get(jenv);
    }

    // Change C++ object's ownership, relative to Java
    void swig_java_change_ownership(JNIEnv *jenv, jobject jself, bool take_or_release) {
      swig_self_.java_change_ownership(jenv, jself, take_or_release);
    }
  };
}

#endif /* __cplusplus */


namespace Swig {
  namespace {
    jclass jclass_LibNeubotJNI = NULL;
    jmethodID director_methids[3];
  }
}

#include "../neubot.hh"



/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "neubot_wrap.h"

SwigDirector_Pollable::SwigDirector_Pollable(JNIEnv *jenv, Neubot::Poller *poller) : Neubot::Pollable(poller), Swig::Director(jenv) {
}

void SwigDirector_Pollable::handle_read() {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  
  if (!swig_override[0]) {
    Neubot::Pollable::handle_read();
    return;
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    jenv->CallStaticVoidMethod(Swig::jclass_LibNeubotJNI, Swig::director_methids[0], swigjobj);
    if (jenv->ExceptionCheck() == JNI_TRUE) return ;
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}

void SwigDirector_Pollable::handle_write() {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  
  if (!swig_override[1]) {
    Neubot::Pollable::handle_write();
    return;
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    jenv->CallStaticVoidMethod(Swig::jclass_LibNeubotJNI, Swig::director_methids[1], swigjobj);
    if (jenv->ExceptionCheck() == JNI_TRUE) return ;
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}

void SwigDirector_Pollable::handle_close() {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  
  if (!swig_override[2]) {
    Neubot::Pollable::handle_close();
    return;
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    jenv->CallStaticVoidMethod(Swig::jclass_LibNeubotJNI, Swig::director_methids[2], swigjobj);
    if (jenv->ExceptionCheck() == JNI_TRUE) return ;
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}

void SwigDirector_Pollable::swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global) {
  static struct {
    const char *mname;
    const char *mdesc;
    jmethodID base_methid;
  } methods[] = {
    {
      "handle_read", "()V", NULL 
    },
    {
      "handle_write", "()V", NULL 
    },
    {
      "handle_close", "()V", NULL 
    }
  };
  
  static jclass baseclass = 0 ;
  
  if (swig_set_self(jenv, jself, swig_mem_own, weak_global)) {
    if (!baseclass) {
      baseclass = jenv->FindClass("org/neubot/swig/Pollable");
      if (!baseclass) return;
      baseclass = (jclass) jenv->NewGlobalRef(baseclass);
    }
    bool derived = (jenv->IsSameObject(baseclass, jcls) ? false : true);
    for (int i = 0; i < 3; ++i) {
      if (!methods[i].base_methid) {
        methods[i].base_methid = jenv->GetMethodID(baseclass, methods[i].mname, methods[i].mdesc);
        if (!methods[i].base_methid) return;
      }
      swig_override[i] = false;
      if (derived) {
        jmethodID methid = jenv->GetMethodID(jcls, methods[i].mname, methods[i].mdesc);
        swig_override[i] = (methid != methods[i].base_methid);
        jenv->ExceptionClear();
      }
    }
  }
}



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_neubot_swig_LibNeubotJNI_new_1EchoServer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jstring jarg4) {
  jlong jresult = 0 ;
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  Neubot::EchoServer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)jenv->GetStringUTFChars(jarg4, 0);
    if (!arg4) return 0;
  }
  result = (Neubot::EchoServer *)new Neubot::EchoServer(arg1,arg2,(char const *)arg3,(char const *)arg4);
  *(Neubot::EchoServer **)&jresult = result; 
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  if (arg4) jenv->ReleaseStringUTFChars(jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_delete_1EchoServer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Neubot::EchoServer *arg1 = (Neubot::EchoServer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Neubot::EchoServer **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->handle_read();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1readSwigExplicitPollable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->Neubot::Pollable::handle_read();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1read_1_1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  Neubot::Pollable::handle_read__(arg1);
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->handle_write();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1writeSwigExplicitPollable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->Neubot::Pollable::handle_write();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1write_1_1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  Neubot::Pollable::handle_write__(arg1);
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1close(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->handle_close();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1closeSwigExplicitPollable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->Neubot::Pollable::handle_close();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1handle_1close_1_1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  Neubot::Pollable::handle_close__(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_neubot_swig_LibNeubotJNI_new_1Pollable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  Neubot::Pollable *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  result = (Neubot::Pollable *)new SwigDirector_Pollable(jenv,arg1);
  *(Neubot::Pollable **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1attach(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  long long arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  arg2 = (long long)jarg2; 
  result = (int)(arg1)->attach(arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1detach(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->detach();
}


SWIGEXPORT jlong JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1fileno(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  long long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  result = (long long)(arg1)->fileno();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1set_1readable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  result = (int)(arg1)->set_readable();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1unset_1readable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  result = (int)(arg1)->unset_readable();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1set_1writable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  result = (int)(arg1)->set_writable();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1unset_1writable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  result = (int)(arg1)->unset_writable();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1set_1timeout(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->set_timeout(arg2);
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1clear_1timeout(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  (arg1)->clear_timeout();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_delete_1Pollable(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Neubot::Pollable *arg1 = (Neubot::Pollable *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Neubot::Pollable **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1director_1connect(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jswig_mem_own, jboolean jweak_global) {
  Neubot::Pollable *obj = *((Neubot::Pollable **)&objarg);
  (void)jcls;
  SwigDirector_Pollable *director = dynamic_cast<SwigDirector_Pollable *>(obj);
  if (director) {
    director->swig_connect_director(jenv, jself, jenv->GetObjectClass(jself), (jswig_mem_own == JNI_TRUE), (jweak_global == JNI_TRUE));
  }
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Pollable_1change_1ownership(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jtake_or_release) {
  Neubot::Pollable *obj = *((Neubot::Pollable **)&objarg);
  SwigDirector_Pollable *director = dynamic_cast<SwigDirector_Pollable *>(obj);
  (void)jcls;
  if (director) {
    director->swig_java_change_ownership(jenv, jself, jtake_or_release ? true : false);
  }
}


SWIGEXPORT jlong JNICALL Java_org_neubot_swig_LibNeubotJNI_new_1Poller(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Neubot::Poller *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Neubot::Poller *)new Neubot::Poller();
  *(Neubot::Poller **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Poller_1sched(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  double arg2 ;
  neubot_hook_vo arg3 ;
  void *arg4 = (void *) 0 ;
  neubot_hook_vo *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  arg2 = (double)jarg2; 
  argp3 = *(neubot_hook_vo **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null neubot_hook_vo");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(void **)&jarg4; 
  result = (int)(arg1)->sched(arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Poller_1defer_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jdouble jarg6) {
  jint jresult = 0 ;
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  long long arg2 ;
  neubot_hook_vo arg3 ;
  neubot_hook_vo arg4 ;
  void *arg5 = (void *) 0 ;
  double arg6 ;
  neubot_hook_vo *argp3 ;
  neubot_hook_vo *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  arg2 = (long long)jarg2; 
  argp3 = *(neubot_hook_vo **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null neubot_hook_vo");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(neubot_hook_vo **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null neubot_hook_vo");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(void **)&jarg5; 
  arg6 = (double)jarg6; 
  result = (int)(arg1)->defer_read(arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Poller_1defer_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jdouble jarg6) {
  jint jresult = 0 ;
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  long long arg2 ;
  neubot_hook_vo arg3 ;
  neubot_hook_vo arg4 ;
  void *arg5 = (void *) 0 ;
  double arg6 ;
  neubot_hook_vo *argp3 ;
  neubot_hook_vo *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  arg2 = (long long)jarg2; 
  argp3 = *(neubot_hook_vo **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null neubot_hook_vo");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(neubot_hook_vo **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null neubot_hook_vo");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(void **)&jarg5; 
  arg6 = (double)jarg6; 
  result = (int)(arg1)->defer_write(arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_neubot_swig_LibNeubotJNI_Poller_1resolve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  neubot_hook_vos arg4 ;
  void *arg5 = (void *) 0 ;
  neubot_hook_vos *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  argp4 = *(neubot_hook_vos **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null neubot_hook_vos");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(void **)&jarg5; 
  result = (int)(arg1)->resolve(arg2,(char const *)arg3,arg4,arg5);
  jresult = (jint)result; 
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Poller_1loop(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  (arg1)->loop();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_Poller_1break_1loop(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Neubot::Poller **)&jarg1; 
  (arg1)->break_loop();
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_delete_1Poller(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Neubot::Poller *arg1 = (Neubot::Poller *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Neubot::Poller **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_org_neubot_swig_LibNeubotJNI_swig_1module_1init(JNIEnv *jenv, jclass jcls) {
  int i;
  
  static struct {
    const char *method;
    const char *signature;
  } methods[3] = {
    {
      "SwigDirector_Pollable_handle_read", "(Lorg/neubot/swig/Pollable;)V" 
    },
    {
      "SwigDirector_Pollable_handle_write", "(Lorg/neubot/swig/Pollable;)V" 
    },
    {
      "SwigDirector_Pollable_handle_close", "(Lorg/neubot/swig/Pollable;)V" 
    }
  };
  Swig::jclass_LibNeubotJNI = (jclass) jenv->NewGlobalRef(jcls);
  if (!Swig::jclass_LibNeubotJNI) return;
  for (i = 0; i < (int) (sizeof(methods)/sizeof(methods[0])); ++i) {
    Swig::director_methids[i] = jenv->GetStaticMethodID(jcls, methods[i].method, methods[i].signature);
    if (!Swig::director_methids[i]) return;
  }
}


#ifdef __cplusplus
}
#endif

