/* Auto-generated by ./script/gen-ffi-macros; don't edit. */
#ifndef MEASUREMENT_KIT_FFI_MACROS_H
#define MEASUREMENT_KIT_FFI_MACROS_H

#define MK_ENUM_EVENTS(XX) \
  XX(failure.asn_lookup, string, false) \
  XX(failure.cc_lookup, string, false) \
  XX(failure.ip_lookup, string, false) \
  XX(failure.measurement, string, false) \
  XX(failure.measurement_submission, string, false) \
  XX(failure.report_create, string, false) \
  XX(failure.report_close, string, false) \
  XX(failure.resolver_lookup, string, false) \
  XX(failure.startup, string, false) \
  XX(log, string, false) \
  XX(measurement, string, false) \
  XX(status.end, string, false) \
  XX(status.geoip_lookup, string, false) \
  XX(status.progress, string, false) \
  XX(status.queued, string, false) \
  XX(status.measurement_start, string, false) \
  XX(status.measurement_submission, string, false) \
  XX(status.measurement_done, string, false) \
  XX(status.report_close, string, false) \
  XX(status.report_create, string, false) \
  XX(status.resolver_lookup, string, false) \
  XX(status.started, string, false) \
  XX(status.update.performance, string, false) \
  XX(status.update.websites, string, false) \
  XX(task_terminated, string, false)

#define MK_ENUM_LOG_LEVELS(XX) \
  XX(ERR, string, false) \
  XX(WARNING, string, false) \
  XX(INFO, string, false) \
  XX(DEBUG, string, false) \
  XX(DEBUG2, string, false)

#define MK_ENUM_OPTIONS(XX) \
  XX(bouncer_base_url, string, false) \
  XX(collector_base_url, string, false) \
  XX(dns/nameserver, string, false) \
  XX(dns/engine, string, false) \
  XX(geoip_asn_path, string, false) \
  XX(geoip_country_path, string, false) \
  XX(ignore_bouncer_error, int, false) \
  XX(ignore_open_report_error, int, false) \
  XX(max_runtime, string, false) \
  XX(net/ca_bundle_path, string, false) \
  XX(net/timeout, string, false) \
  XX(no_bouncer, int, false) \
  XX(no_collector, int, false) \
  XX(no_asn_lookup, int, false) \
  XX(no_cc_lookup, int, false) \
  XX(no_ip_lookup, int, false) \
  XX(no_file_report, int, false) \
  XX(no_resolver_lookup, int, false) \
  XX(probe_asn, string, false) \
  XX(probe_cc, string, false) \
  XX(probe_ip, string, false) \
  XX(randomize_input, int, false) \
  XX(save_real_probe_asn, int, false) \
  XX(save_real_probe_cc, int, false) \
  XX(save_real_probe_ip, int, false) \
  XX(save_real_resolver_ip, int, false) \
  XX(software_name, string, false) \
  XX(software_version, string, false)

#define MK_ENUM_SETTINGS(XX) \
  XX(annotations, object, false) \
  XX(disabled_events, array, false) \
  XX(inputs, array, false) \
  XX(input_filepaths, array, false) \
  XX(log_filepath, string, false) \
  XX(log_level, string, false) \
  XX(name, string, true) \
  XX(options, object, false) \
  XX(output_filepath, string, false)

#define MK_ENUM_TASKS(XX) \
  XX(Dash, string, false) \
  XX(CaptivePortal, string, false) \
  XX(DnsInjection, string, false) \
  XX(FacebookMessenger, string, false) \
  XX(HttpHeaderFieldManipulation, string, false) \
  XX(HttpInvalidRequestLine, string, false) \
  XX(MeekFrontedRequests, string, false) \
  XX(MultiNdt, string, false) \
  XX(Ndt, string, false) \
  XX(TcpConnect, string, false) \
  XX(Telegram, string, false) \
  XX(WebConnectivity, string, false) \
  XX(Whatsapp, string, false)

#endif /* MEASUREMENT_KIT_FFI_MACROS_H */
