#!/bin/sh
set -e

if [ $# -ne 0 ]; then
    echo "usage: $0" 1>&2
    exit 1
fi
REPOROOT=$(cd $(dirname $0)/../../ && pwd -P)
cd $REPOROOT

debian_deps="$debian_deps cmake"
debian_deps="$debian_deps g++"
debian_deps="$debian_deps git"
debian_deps="$debian_deps libc-ares-dev"
debian_deps="$debian_deps libevent-dev"
debian_deps="$debian_deps libgeoip-dev"
debian_deps="$debian_deps libssl-dev"
debian_deps="$debian_deps make"
debian_deps="$debian_deps wget"

set -x # Log commands we run

apt-get update
apt-get upgrade -y
apt-get install -y $debian_deps

./autogen.sh --cmake
cmake .
make V=0 -j$(nproc)
ctest -j6 --output-on-failure
