#!/bin/sh
set -e

if [ $# -ne 0 ]; then
    echo "usage: $0" 1>&2
    exit 1
fi
REPOROOT=$(cd $(dirname $0)/../../ && pwd -P)
cd $REPOROOT

debian_deps="$debian_deps cmake"
debian_deps="$debian_deps g++"
debian_deps="$debian_deps git"
debian_deps="$debian_deps libc-ares-dev"
debian_deps="$debian_deps libevent-dev"
debian_deps="$debian_deps libgeoip-dev"
debian_deps="$debian_deps libssl-dev"
debian_deps="$debian_deps make"
debian_deps="$debian_deps wget"
#debian_deps="$debian_deps iproute2"
debian_deps="$debian_deps iptables"

set -x # Log commands we run

apt-get update
apt-get upgrade -y
apt-get install -y $debian_deps

#ip address show
#tc qdisc add dev eth0 root tbf rate 220kbit latency 50ms burst 1540
tc qdisc change dev eth0 root netem delay 100ms 10ms
#iptables -A INPUT -m statistic --mode random --probability 0.005 -j DROP
#iptables -A OUTPUT -m statistic --mode random --probability 0.005 -j DROP

./autogen.sh --cmake
./build/cmake/cmake -DMK_BUILD_TESTS=OFF
make V=0 -j$(nproc)
./measurement_kit ndt
#ctest -j6 --output-on-failure
