#!/bin/sh
set -e
REPOROOT=$(cd $(dirname $0)/../../ && pwd -P)

if [ $# -ne 2 ]; then
  echo "usage: $0 docker-image-name script-name" 1>&2
  exit 1
fi

docker_image=$1
script_name=$2

# With travis we cannot set CC and CXX directly
if [ "$TRAVIS_BRANCH" != "" ]; then
  if [ "$MK_CC" != "" ]; then
    CC=$MK_CC
  fi
  if [ "$MK_CXX" != "" ]; then
    CXX=$MK_CXX
  fi
fi

docker run                                                                 \
    --cap-add=NET_ADMIN                                                    \
    -e "CC=$CC"                                                            \
    -e "CMAKE_OPTIONS=$CMAKE_OPTIONS"                                      \
    -e "CXX=$CXX"                                                          \
    -e "CPPFLAGS=$CPPFLAGS"                                                \
    -e "CFLAGS=$CFLAGS"                                                    \
    -e "CXXFLAGS=$CXXFLAGS"                                                \
    -e "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN"                        \
    -e "TRAVIS_BRANCH=$TRAVIS_BRANCH"                                      \
    -v $REPOROOT:/mk                                                       \
    $docker_image                                                          \
    /mk/.ci/docker/$script_name
