/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.neubot.swig;

public class EchoServer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EchoServer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EchoServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibNeubotJNI.delete_EchoServer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EchoServer(Poller poller, int use_ipv6, String address, String port) {
    this(LibNeubotJNI.new_EchoServer(Poller.getCPtr(poller), poller, use_ipv6, address, port), true);
  }

}
