/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.neubot.swig;

public class LibNeubotJNI {
  public final static native long new_EchoServer(long jarg1, Poller jarg1_, int jarg2, String jarg3, String jarg4);
  public final static native void delete_EchoServer(long jarg1);
  public final static native void Pollable_handle_read(long jarg1, Pollable jarg1_);
  public final static native void Pollable_handle_write(long jarg1, Pollable jarg1_);
  public final static native void Pollable_handle_close(long jarg1, Pollable jarg1_);
  public final static native long new_Pollable(long jarg1, Poller jarg1_);
  public final static native int Pollable_attach(long jarg1, Pollable jarg1_, long jarg2);
  public final static native void Pollable_detach(long jarg1, Pollable jarg1_);
  public final static native long Pollable_fileno(long jarg1, Pollable jarg1_);
  public final static native int Pollable_set_readable(long jarg1, Pollable jarg1_);
  public final static native int Pollable_unset_readable(long jarg1, Pollable jarg1_);
  public final static native int Pollable_set_writable(long jarg1, Pollable jarg1_);
  public final static native int Pollable_unset_writable(long jarg1, Pollable jarg1_);
  public final static native void Pollable_set_timeout(long jarg1, Pollable jarg1_, double jarg2);
  public final static native void Pollable_clear_timeout(long jarg1, Pollable jarg1_);
  public final static native void delete_Pollable(long jarg1);
  public final static native void Pollable_director_connect(Pollable obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Pollable_change_ownership(Pollable obj, long cptr, boolean take_or_release);
  public final static native long new_Poller();
  public final static native void Poller_loop(long jarg1, Poller jarg1_);
  public final static native void Poller_break_loop(long jarg1, Poller jarg1_);
  public final static native void delete_Poller(long jarg1);

  public static void SwigDirector_Pollable_handle_read(Pollable self) {
    self.handle_read();
  }
  public static void SwigDirector_Pollable_handle_write(Pollable self) {
    self.handle_write();
  }
  public static void SwigDirector_Pollable_handle_close(Pollable self) {
    self.handle_close();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
