/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.neubot.swig;

public class SWIGTYPE_p_neubot_hook_vos {
  private long swigCPtr;

  protected SWIGTYPE_p_neubot_hook_vos(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_neubot_hook_vos() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_neubot_hook_vos obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

