/*
 * Libight interface - Public domain.
 * WARNING: Autogenerated file - do not edit!
 */

#ifndef IGHT_WRAPPERS_H
# define IGHT_WRAPPERS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Hooks and slots: */

typedef void (*ight_hook_vo)(void *);
typedef void (*ight_hook_vos)(void *, const char *);

typedef void (*ight_slot_vo)(void *);

struct evbuffer;

/* Classes: */

struct IghtPoller;

/* IghtPoller API: */

struct IghtPoller *IghtPoller_construct(void);

int IghtPoller_sched(struct IghtPoller *, double, ight_hook_vo, void *);

int IghtPoller_defer_read(struct IghtPoller *, long long, ight_hook_vo,
    ight_hook_vo, void *, double);

int IghtPoller_defer_write(struct IghtPoller *, long long, ight_hook_vo,
    ight_hook_vo, void *, double);

int IghtPoller_resolve(struct IghtPoller *, const char *, const char *,
    ight_hook_vos, void *);

void IghtPoller_loop(struct IghtPoller *);

void IghtPoller_break_loop(struct IghtPoller *);

#ifdef __cplusplus
}
#endif

#endif  /* IGHT_WRAPPERS_H */
