/* libneubot/libneubot.cpp */

/*-
 * Copyright (c) 2013-2014
 *     Nexa Center for Internet & Society, Politecnico di Torino (DAUIN)
 *     and Simone Basso <bassosimone@gmail.com>.
 *
 * This file is part of Neubot <http://www.neubot.org/>.
 *
 * Neubot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Neubot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Neubot.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// Libneubot C wrappers for C++
//
// Ideally this file should be as much autogenerated as possible
//

#include <new>
#include <stdlib.h>

#include <event2/event.h>

#include "ight_wrappers.h"

#include "common/stringvector.h"
#include "common/log.h"

#include "net/connection.h"
#include "net/protocol.h"

#include "neubot/pollable.hh"

//
// Pollable
//

struct IghtPollableWrapper : public IghtPollable {

	ight_slot_vo on_handle_error;
	ight_slot_vo on_handle_read;
	ight_slot_vo on_handle_write;
	void *opaque;

	IghtPollableWrapper(IghtPoller *poller, ight_slot_vo on_read,
	    ight_slot_vo on_write, ight_slot_vo on_error,
	    void *opaque) : IghtPollable(poller) {
		ight_info("IghtPollable::construct");
		this->on_handle_error = on_error;
		this->on_handle_read = on_read;
		this->on_handle_write = on_write;
		this->opaque = opaque;
	};

	virtual void handle_read(void) {
		ight_info("IghtPollable::handle_read");
		this->on_handle_read(this->opaque);
	};

	virtual void handle_write(void) {
		ight_info("IghtPollable::handle_write");
		this->on_handle_write(this->opaque);
	};

	virtual void handle_error(void) {
		ight_info("IghtPollable::handle_error");
		this->on_handle_error(this->opaque);
	};

	virtual ~IghtPollableWrapper(void) {
		ight_info("IghtPollable::~IghtPollable");
	};
};

IghtPollable *
IghtPollable_construct(IghtPoller *poller, ight_slot_vo handle_read,
    ight_slot_vo handle_write, ight_slot_vo handle_error,
    void *opaque)
{
	if (poller == NULL)
		abort();

	try {
		return (new IghtPollableWrapper(poller, handle_read, handle_write,
		    handle_error, opaque));
	} catch (...) {
		return (NULL);
	}
}

int
IghtPollable_attach(IghtPollable *self, long long fileno)
{
	if (self == NULL)
		abort();

	return (self->attach(fileno));
}

void
IghtPollable_detach(IghtPollable *self)
{
	if (self == NULL)
		abort();

	self->detach();
}

long long
IghtPollable_get_fileno(IghtPollable *self)
{
	if (self == NULL)
		abort();

	return (self->get_fileno());
}

int
IghtPollable_set_readable(IghtPollable *self)
{
	if (self == NULL)
		abort();

	return (self->set_readable());
}

int
IghtPollable_unset_readable(IghtPollable *self)
{
	if (self == NULL)
		abort();

	return (self->unset_readable());
}

int
IghtPollable_set_writable(IghtPollable *self)
{
	if (self == NULL)
		abort();

	return (self->set_writable());
}

int
IghtPollable_unset_writable(IghtPollable *self)
{
	if (self == NULL)
		abort();

	return (self->unset_writable());
}

void
IghtPollable_set_timeout(IghtPollable *self, double timeout)
{
	if (self == NULL)
		abort();

	self->set_timeout(timeout);
}

void
IghtPollable_clear_timeout(IghtPollable *self)
{
	if (self == NULL)
		abort();

	self->clear_timeout();
}

void
IghtPollable_close(IghtPollable *self)
{
	if (self == NULL)
		abort();

	delete (self);
}

//
// Protocol
//

struct IghtProtocolWrapper : public IghtProtocol {

	IghtPoller *poller;
	ight_slot_vo fn_connect;
	ight_slot_vo fn_ssl;
	ight_slot_vo fn_data;
	ight_slot_vo fn_flush;
	ight_slot_vo fn_eof;
	ight_slot_vo fn_error;
	void *opaque;

	IghtProtocolWrapper(IghtPoller *p, ight_slot_vo slot_connect,
	    ight_slot_vo slot_ssl, ight_slot_vo slot_data,
	    ight_slot_vo slot_flush, ight_slot_vo slot_eof,
	    ight_slot_vo slot_error, void *o) : IghtProtocol() {
		this->poller = p;
		this->fn_connect = slot_connect;
		this->fn_ssl = slot_ssl;
		this->fn_data = slot_data;
		this->fn_flush = slot_flush;
		this->fn_eof = slot_eof;
		this->fn_error = slot_error;
		this->opaque = o;
	}

	virtual void on_connect(void) {
		if (this->fn_connect != NULL)
			this->fn_connect(this->opaque);
	}

	virtual void on_ssl(void) {
		if (this->fn_ssl != NULL)
			this->fn_ssl(this->opaque);
	}

	virtual void on_data(void) {
		if (this->fn_data != NULL)
			this->fn_data(this->opaque);
	}

	virtual void on_flush(void) {
		if (this->fn_flush != NULL)
			this->fn_flush(this->opaque);
	}

	virtual void on_eof(void) {
		if (this->fn_eof != NULL)
			this->fn_eof(this->opaque);
	}

	virtual void on_error(void) {
		if (this->fn_error != NULL)
			this->fn_error(this->opaque);
	}

	// Defined out-of-line to avoid -Wweak-vtables warning
	virtual IghtPoller *get_poller(void);
};

// Defined here to avoid -Wweak-vtables warning
IghtPoller *
IghtProtocolWrapper::get_poller(void)
{
	return (this->poller);
}

IghtProtocol *
IghtProtocol_construct(IghtPoller *p, ight_slot_vo slot_connect,
    ight_slot_vo slot_ssl, ight_slot_vo slot_data,
    ight_slot_vo slot_flush, ight_slot_vo slot_eof,
    ight_slot_vo slot_error, void *o)
{
	if (p == NULL)
		abort();

	return (new (std::nothrow) IghtProtocolWrapper(p, slot_connect,
	    slot_ssl, slot_data, slot_flush, slot_eof, slot_error, o));
}

IghtPoller *
IghtProtocol_get_poller(IghtProtocol *self)
{
	if (self == NULL)
		abort();

	return (self->get_poller());
}

void
IghtProtocol_destruct(IghtProtocol *self)
{
	if (self == NULL)
		abort();

	delete (self);
}

//
// Connection
//

IghtConnection *
IghtConnection_attach(IghtProtocol *proto, long long filenum)
{
	return (IghtConnection::attach(proto, filenum));
}

IghtConnection *
IghtConnection_connect(IghtProtocol *proto, const char *family,
    const char *address, const char *port)
{
	return (IghtConnection::connect(proto, family, address, port));
}

IghtConnection *
IghtConnection_connect_hostname(IghtProtocol *proto, const char *family,
    const char *address, const char *port)
{
	return (IghtConnection::connect_hostname(proto,
	    family, address, port));
}

IghtProtocol *
IghtConnection_get_protocol(IghtConnection *self)
{
	if (self == NULL)
		abort();

	return (static_cast<IghtProtocol *>(self->get_protocol()));
}

int
IghtConnection_set_timeout(IghtConnection *self, double timeo)
{
	if (self == NULL)
		abort();

	return (self->set_timeout(timeo));
}

int
IghtConnection_clear_timeout(IghtConnection *self)
{
	if (self == NULL)
		abort();

	return (self->clear_timeout());
}

int
IghtConnection_start_tls(IghtConnection *self, unsigned server_side)
{
	if (self == NULL)
		abort();

	return (self->start_tls(server_side));
}

int
IghtConnection_read(IghtConnection *self, char *base, size_t count)
{
	if (self == NULL)
		abort();

	return (self->read(base, count));
}

int
IghtConnection_readline(IghtConnection *self, char *base, size_t count)
{
	if (self == NULL)
		abort();

	return (self->readline(base, count));
}

int
IghtConnection_readn(IghtConnection *self, char *base, size_t count)
{
	if (self == NULL)
		abort();

	return (self->readn(base, count));
}

int
IghtConnection_discardn(IghtConnection *self, size_t count)
{
	if (self == NULL)
		abort();

	return (self->discardn(count));
}

int
IghtConnection_write(IghtConnection *self, const char *base, size_t count)
{
	if (self == NULL)
		abort();

	return (self->write(base, count));
}

int
IghtConnection_puts(IghtConnection *self, const char *str)
{
	if (self == NULL)
		abort();

	return (self->puts(str));
}

int
IghtConnection_write_rand(IghtConnection *self, size_t count)
{
	if (self == NULL)
		abort();

	return (self->write_rand(count));
}

int
IghtConnection_write_readbuf(IghtConnection *self, const char *base, size_t count)
{
	if (self == NULL)
		abort();

	return (self->write_readbuf(base, count));
}

int
IghtConnection_puts_readbuf(IghtConnection *self, const char *str)
{
	if (self == NULL)
		abort();

	return (self->puts_readbuf(str));
}

int
IghtConnection_write_rand_readbuf(IghtConnection *self, size_t count)
{
	if (self == NULL)
		abort();
	return (self->write_rand_readbuf(count));
}

int
IghtConnection_read_into_(IghtConnection *self, evbuffer *dest)
{
	if (self == NULL)
		abort();

	return (self->read_into_(dest));
}

int
IghtConnection_write_from_(IghtConnection *self, evbuffer *source)
{
	if (self == NULL)
		abort();

	return (self->write_from_(source));
}

int
IghtConnection_enable_read(struct IghtConnection *self)
{
	if (self == NULL)
		abort();

	return (self->enable_read());
}

int
IghtConnection_disable_read(struct IghtConnection *self)
{
	if (self == NULL)
		abort();

	return (self->disable_read());
}

void
IghtConnection_close(IghtConnection *self)
{
	if (self == NULL)
		abort();

	self->close();
}

//
// StringVector
//

IghtStringVector *
IghtStringVector_construct(IghtPoller *poller, size_t count)
{
	return (new (std::nothrow) IghtStringVector(poller, count));
}

int
IghtStringVector_append(IghtStringVector *self, const char *str)
{
	if (self == NULL)
		abort();

	return (self->append(str));
}

IghtPoller *
IghtStringVector_get_poller(IghtStringVector *self)
{
	if (self == NULL)
		abort();

	return (self->get_poller());
}

const char *
IghtStringVector_get_next(IghtStringVector *self)
{
	if (self == NULL)
		abort();

	return (self->get_next());
}

void
IghtStringVector_destruct(IghtStringVector *self)
{
	if (self == NULL)
		abort();

	delete (self);
}
